name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          # Copy all project files to VPS
          scp -i ~/.ssh/id_rsa -r . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/smartmenu

          # Execute deployment commands on VPS
          ssh -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /var/www/smartmenu/elbaron-bns

            # Deploy server
            cd server
            git pull origin main
            npm install
            npm run build

            # Deploy client
            cd ../client
            git pull origin main
            npm install
            npm run build
          EOF
